@startuml
'https://plantuml.com/sequence-diagram

class TodoListApplication{
    +start;
    +main;
}
class ApplicationsController{
    -ArrayList<String> todoList
    -TextField completed
    -DatePicker date
    -TextField description
    -Button newButton
    -Button openButton
    -Button removeButton
    -Button saveButton
    -Button showAllButton
    -Button showCompletedButton
    -Button showUncompletedButton
    -TableView<todoItem> tableOfItems
    -TableColumn<todoItem, String> tableDate
    -TableColumn<todoItem, String> tableDescription
    -TableColumn<todoItem, String> tableComplete
    -Button clearButton
    +ArrayList getTodoList()
    +initialize(URL location, ResourceBundle resources)
    +int CompletedButtonClicked(ActionEvent event)
    +ArrayList<String> clickAddTodoList(ActionEvent event)
    +clickedSaveFile(ActionEvent event)
    +int clickedShowUncompleted(Action event)
    +openFileClicked(ActionEvent event)
    +ArrayList<String>removeClicked(ActionEvent event)
    +int showAllClicked(ActionEvent event)
    +clearedButtonClicked(ActionEvent event)

}
class addItems{
    -ArrayList<String> newTodoList
    +ArrayList<String> addTask(LocalDate date, String description, String completed,ArrayList todoList)
}

class clearEverything{
    +ArrayList<String> clearArrayList();
}
class fileSaver{
    +savingFile(File file, ArrayList savedList);
}
class modifyShown{
    +ArrayList modifyArrayList(ArrayList oldArrayList, String newText, String oldText, int number);
}
class parsedOpenedFile{
    +parseInformation(String words);
    +String getDate();
    +String getDescription();
    +String getCompleted();
}
class removeItems{
    -ArrayList<String> newTodoList
    +ArrayList removeTask(String value, ArrayList todoList);
}
class showSomething{
    +int showNonCompleted(String words)
    +String getDate();
    +String getDescription();
    +String getCompleted();
}
class todoItem{
    -SimpleStringProperty date
    -SimpleStringProperty description
    -SimpleStringProperty Complete
    +todItem(String date, String description, String complete);
    +String getDate()
    +setDate(String newDate)
    +String getDescription()
    +setDescription(String description)
    +String getComplete()
    +setComplete(String completed)
}
ApplicationsController --- TodoListApplication
ApplicationsController --- addItems
ApplicationsController --- clearEverything
ApplicationsController --- fileSaver
ApplicationsController --- modifyShown
ApplicationsController --- parsedOpenedFile
ApplicationsController --- removeItems
ApplicationsController --- showSomething
ApplicationsController --- todoItem

@enduml