@startuml
'https://plantuml.com/sequence-diagram

class Applications{
    +start;
    +main;
}
class ApplicationsController{
    -ArrayList<String> todoList

    -Button addTodoListButton;
    -Button buttonSaveName;
    -DatePicker date;
    -TextField description;
    - Button newButton;
    -TextField newTitle;
    -Button openButton;
    -Button removeButton;
    -TextField removeNumber;
    -Button saveButton;
    -Button showAllButton;
    -Button showCompletedButton;
    -Button showUncompletedButton;
    -TableColumn<?, ?> tableComplete;
    -TableColumn<?, ?> tableDate;
    -TableColumn<?, ?> tableDescription;
    -TextField editInfoCompleted;
    -Button editDataButton
    -DatePicker editedDate
    -TextField editedDescription
    -TextField lineNumberEditInformation
    +ArrayList<String> getTodoList
    +int CompletedButtonClicked(ActionEvent event)
    +ArrayList<String> removeClicked(ActionEvent event)
    +int showAllClicked(ActionEvent event)
    +int clickedEditInformation(ActionEvent event)
    +ArrayList<String> clickAddTodoList(ActionEvent event)
    +clickedSaveFile(ActionEvent event)
    +clickedSaveName(ActionEvent event)
    +int clickedShowUncompleted(ActionEvent event)
    +newFileClicked(ActionEvent event)
    +openFileClicked(ActionEvent event)

}
class addItems{
    -ArrayList<String> newTodoList
    +ArrayList<String> addTask(String date,String description, int completed )
}
class removeItems{
    -ArrayList<String> newTodoList
    +ArrayList<String> removeTask(int indexNumber)
}
class openNewFile{
    +openNewFile(String fileName)

}
class saveFile{
     +saveFile(String fileName)
}
class showNonCompleted{
    -int counter
    +int showNonCompleted()
}
class showAll{
    -int counter
     +int showAll()
}
class showCompleted{
    -int counter
    +int showComplete()
}
class openFile{
    +openFile(String fileName)
}
class setTitle{
   +String setTitle(String title)

}
class editDate{
    -ArrayList<String> newTodoList
    +ArrayList<String> editDate(String newDate ,int index)

}
class editDescription{
    -ArrayList<String> newTodoList
    +ArrayList<String> editDescription(String newDescription, int index)
}
class editCompleted{
    -ArrayList<String> newTodoList
    +ArrayList<String> editCompleted(int completed, int index)

}

Applications --- ApplicationsController
ApplicationsController <|-- addItems
ApplicationsController <|-- removeItems
ApplicationsController <|-- openNewFile
ApplicationsController <|-- saveFile
ApplicationsController <|-- showNonCompleted
ApplicationsController <|-- showAll
ApplicationsController <|-- showCompleted
ApplicationsController <|-- openFile
ApplicationsController <|-- setTitle
ApplicationsController <|-- editDate
ApplicationsController <|-- editDescription
ApplicationsController <|-- editCompleted
@enduml